[global]
name = "node0.demo"
ca_file = "include/auth-ca.crt"
certificate_file = "include/node0-noise.crt"
private_key_file = "include/node0-noise.key"
self_addr = "0.0.0.0:5000"
zpr_addr = [ "fd5a:5052:90de::10" ]
tun_if = "tun9"

[authentication]
auth_private_key = "include/node0-private-key.pem"
