#!/usr/bin/env bash
# Build ph/vs/vsapikey for Oracle Linux 9 (glibc 2.34) inside an OL9 container.
#
# Why: binaries built on the dev laptop link against a newer glibc (2.38/2.39)
# and will NOT run on OL9 ("GLIBC_2.38 not found"). Building in an oraclelinux:9
# container links against glibc 2.34, matching the OCI compute instances.
# musl static builds were ruled out — ph/vs pull in openssl-sys + aws-lc-sys
# (cmake-built C crypto), which fight musl.
#
# Source trees are mounted READ-ONLY and output goes to $ZPR_BUILD_DIR, so this
# never touches your working trees or their target/ dirs. The two workspaces are
# mounted separately (they share no relative path deps), so both the split-repo
# layout (~/src/zpr-core + ~/src/zpr-visaservice) and the monorepo layout
# (zpr/core + zpr/visaservice) work — see sources.env.example.
#
# Writes binaries.auto.tfvars so tofu picks up the output paths automatically.
#
# Requires Docker (via sudo on this host) plus outbound network AND git access
# from inside the container — zpr-visaservice pulls zpr-common from GitHub.
# Run from anywhere.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
[ -f "$HERE/sources.env" ] && . "$HERE/sources.env"

ZPR_CORE_SRC="${ZPR_CORE_SRC:?set ZPR_CORE_SRC (cp sources.env.example sources.env and edit)}"
ZPR_VS_SRC="${ZPR_VS_SRC:?set ZPR_VS_SRC (cp sources.env.example sources.env and edit)}"
ZPR_BUILD_DIR="${ZPR_BUILD_DIR:-$HOME/.cache/zpr-oci-build}"

[ -f "$ZPR_CORE_SRC/Cargo.toml" ] || { echo "not a zpr-core checkout: $ZPR_CORE_SRC" >&2; exit 1; }
[ -f "$ZPR_VS_SRC/Cargo.toml" ]   || { echo "not a zpr-visaservice checkout: $ZPR_VS_SRC" >&2; exit 1; }
mkdir -p "$ZPR_BUILD_DIR"

# One shared CARGO_TARGET_DIR for two workspaces: ph and vs/vsapikey don't collide
# by name and neither build removes the other's output. Cost is recompiling shared
# deps between the two. --locked fails loudly on a stale Cargo.lock (which the
# read-only mounts couldn't update anyway) — the right behaviour for a release build.
sudo docker run --rm \
  -v "$ZPR_CORE_SRC:/src/core:ro" \
  -v "$ZPR_VS_SRC:/src/vs:ro" \
  -v "$ZPR_BUILD_DIR:/out" \
  -w /src -e CARGO_TARGET_DIR=/out/target oraclelinux:9 bash -c '
  set -e
  # oracle-epel-release-el9 defines the EPEL repo (disabled); capnproto lives there.
  # libpcap-devel lives in CodeReady Builder (also disabled). Enable both to install.
  dnf install -y oracle-epel-release-el9
  dnf install -y --enablerepo=ol9_developer_EPEL,ol9_codeready_builder \
    gcc gcc-c++ cmake perl openssl-devel pkgconf-pkg-config capnproto libpcap-devel git
  curl --proto "=https" --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  . "$HOME/.cargo/env"
  cargo build --release --locked --manifest-path core/Cargo.toml
  cargo build --release --locked --manifest-path vs/Cargo.toml
  # container runs as root; hand the output back to the owner of the mounted dir
  chown -R $(stat -c %u:%g /out) /out
'

REL="$ZPR_BUILD_DIR/target/release"

# Generated, not hand-maintained: variables.tf has no defaults for these, so the
# build output location is stated exactly once. Otherwise the two drift and you
# deploy a binary from a previous build with no error.
cat > "$HERE/binaries.auto.tfvars" <<EOF
# GENERATED by build-in-ol9.sh — do not edit. Gitignored.
ph_binary_path       = "$REL/ph"
vs_binary_path       = "$REL/vs"
vsapikey_binary_path = "$REL/vsapikey"
EOF

echo
echo "Built:"
ls -la "$REL/ph" "$REL/vs" "$REL/vsapikey"
echo "Wrote $HERE/binaries.auto.tfvars"
echo "Verify glibc requirement is <= 2.34:"
objdump -T "$REL/ph" | grep -oE 'GLIBC_[0-9]+\.[0-9]+' | sort -V | tail -1
